my_school/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, include

from courseapp.views import AllCoursesListView
from .settings import STATIC_URL


urlpatterns = [
    re_path(r'^$', AllCoursesListView.as_view(), name='index'),
    re_path(r'^course/', include('courseapp.urls', namespace='course')),

    re_path(r'^admin/', admin.site.urls),
] + static(STATIC_URL)

my_school/courseapp/urls.py
from django.urls import re_path

from courseapp.views import CourseDetailView


app_name = 'courseapp'

urlpatterns = [
    re_path(r'(?P<pk>\d+)/$', CourseDetailView.as_view(), name='page')
]

my_school/mainapp/urls.py
from django.urls import re_path


app_name = 'mainapp'

urlpatterns = [
]

my_school/authapp/models.py
from django.db import models

my_school/courseapp/models.py
from django.db import models


class Course(models.Model):
    EASY = 'e'
    NORMAL = 'n'
    HARD = 'h'

    LEVELS = [
        (EASY, 'Для новичков'),
        (NORMAL, 'Не придумал для кого'),
        (HARD, 'Для старичков')
    ]

    name = models.CharField(
        max_length=512,
        blank=True,
        verbose_name='название',
        unique=True
    )
    description = models.TextField(
        blank=True,
        verbose_name='описание'
    )
    img = models.CharField(
        max_length=32,
        blank=True,
        verbose_name="фото",
    )
    price = models.IntegerField(
        null=False,
        verbose_name='цена',
        default=999
    )
    author = models.CharField(
        max_length=32,
        blank=True,
        verbose_name='автор'
    )
    level = models.CharField(
        max_length=1,
        choices=LEVELS,
        default=EASY
    )
    date = models.DateField(
        auto_created=True,
        verbose_name='дата создания'
    )

    def __str__(self):
        return self.name

my_school/mainapp/models.py
from django.db import models

my_school/authapp/views.py
from django.shortcuts import render

# Create your views here.

my_school/courseapp/views.py
from django.views.generic import DetailView, ListView

from .models import Course


class AllCoursesListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course

my_school/courseapp/templates/courseapp/course_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block title %}
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static '/css/course-page.css' %}">
{% endblock css %}

{% block content %}
    <section class="course-page">
        <div class="course-info">
            <h1 class="course-title">{{ object.name }}</h1>
            <span class="for-author">Курс разработан:</span>
            <div class="author-info">
                <img src="{% static '/img/person-circle-outline.svg' %}" alt="" class="author-avatar">
                <h2 class="author-name">{{ object.author }}</h2>
            </div>
            <p class="course-descr">{{ object.description }}</p>
        </div>
        <a href="#" class="start btn btnPrimary">Начать учиться!</a>
    </section>
{% endblock content %}

my_school/courseapp/templates/courseapp/course_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block title %}
    Школа
{% endblock title %}

{% block content  %}
<section class="all-courses">
    {% for course in object_list %}
        <article class="course">
            <img src="{% static '/img/course1.png' %}" alt="" class="course-img">
            <div class="author-info">
                <img src="{% static '/img/person-circle-outline.svg' %}" alt="" class="author-avatar">
                <h2 class="author-name">Sasha Vidyakov</h2>
            </div>
            <h2 class="course-title">{{ course.name }}</h2>
            <div class="course-info">
                <div class="level-info">
                    <div class="level"></div>
                    <span class="level-title">Начальный</span>
                </div>
                <a href="{% url 'course:page' course.pk %}" class="start-learning">Начать<img
                        src="{% static '/img/arrow-forward-outline.svg' %}" alt=""></a>
            </div>
        </article>
    {% endfor %}
</section>
{% endblock content %}

my_school/mainapp/templates/mainapp/base.html
<!DOCTYPE html>

{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    {% block css %}
    {% endblock css %}
    {% block js %}
    {% endblock js %}
</head>
<body>
    <header>
        <nav class="header">
            <a href="{% url 'index' %}" class="logo logo-title"><img src="{% static '/img/library-outline.svg' %}" alt="" class="logo-img">Школа</a>

            <div class="right-side">
                <div class="nav-search">
                    <input type="text" placeholder="Что вы хотите выучить?">
                    <img src="{% static '/img/search-outline.svg' %}" alt="">
                </div>
                <a href="#" class="btn">Войти</a>
                <a href="#" class="btn btnPrimary">Зарегистрироваться</a>
            </div>
        </nav>
    </header>
    <main>
        <div class="wrapper-content">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer>

    </footer>
</body>
</html>